### ISSUE TITLE
rpc

### ISSUE THREAD

**Issue by adiit01** [Shardeum/shardeum-bug-reporting#1] opened 2022-10-24 19:22 UTC
Rpc sometimes slow

**Comment by MarcusWentz** [comment] 2022-11-09 02:22
Shardeum testnets are being updated soon to fix RPC issues.

Please use the following format for bug reports:
https://github.com/Shardeum/shardeum-bug-reporting#how-to-report-a-bug

Closing issue for now since the issue is being worked on.

**Closed by MarcusWentz** 2022-11-09 02:22 UTC
