### ISSUE TITLE
Validator remove stake/add stake

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#326] opened 2023-04-13 10:34 UTC
##### What is the issue?

i can not remove my stake to start my validator running again
    
#### What impact does the issue have?

can not run validator

##### How to reproduce the issue? 
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Maximum load exceeded.","data":{"originalError":{"status":500}}}}}'

**Comment by Balasuriya55** [comment] 2023-04-13 12:37
Hey team am run the node in mobile i have updated latest version am trying to unstake but [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Maximum load exceeded.","data":{"originalError":{"status":500}}}}}'. This error came am try force unstake and my wallet also resetted but still cannot unstake and stake

**Comment by Brave-Humens** [comment] 2023-04-13 15:52
We also have this problem: when we want to upgrade to 1.1.7 we need first of all unstake with command:
`node@2c51dcbb73ef:~/app$ operator-cli unstake`
but we have this answer:
```
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":53,\"error\":{\"code\":101,\"message\":\"Maximum load exceeded.\",\"data\":{\"originalError\":{\"status\":500}}}}", error={"code":101,"data":{"originalError":{"status":500}}}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf9013f808501dfd140008401c9c38094000000000000000000000000000000000000000180b8d67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307866333131396664333934326664623961326562646139396462353964313833666131653166646565222c2274696d657374616d70223a313638313430303432363537392c226e6f6d696e6565223a2237623434326236323634656333326533356432316637376264656638356237333030363639666465316531656637323862666135623231343165646430613165222c22666f726365223a66616c73657d823f48a02f2e7693d936e015ba933eceaa958fa6661146c8fede760fb934fd1971ab51a4a0419aed4c78a06c094d8895255dfbaf18891723fc8dd3f8a58544a1a26e7574e4\"],\"id\":53,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://sphinx.shardeum.org", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:313:32
    at step (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":53,"error":{"code":101,"message":"Maximum load exceeded.","data":{"originalError":{"status":500}}}}',
  error: Error: Maximum load exceeded.
      at getResult (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
      at processJsonFunc (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:356:22)
      at /home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:288:46
      at step (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: 101,
    data: { originalError: [Object] }
  },
```
please say what we need to successfully unstake and upgrade node!

**Comment by rafalbujak** [comment] 2023-04-13 16:51
I have seen this ame error as @Balasuriya55 plus in my metamask this issue: 
![Bez tytułu](https://user-images.githubusercontent.com/35694443/231828756-67ebb3bf-ba5d-4948-b1dc-0f62cd3ba95a.jpg)

adding staiking is not possible at the moment and takes a very long time after the update to the new version.

in addition, immediately after starting the node showed me this erorr in the console

Error:
`node@a93bff51db2f:~/app$ operator-cli start
node@a93bff51db2f:~/app$ operator-cli status
AxiosError: connect ECONNREFUSED 127.0.0.1:9001
    at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (node:events:402:35)
    at ClientRequest.eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  port: 9001,
  address: '127.0.0.1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 2000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://127.0.0.1:9001/nodeinfo',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/nodeinfo',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '127.0.0.1',
      port: '9001',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/nodeinfo'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /nodeinfo HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 127.0.0.1:9001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/nodeinfo',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://127.0.0.1:9001/nodeinfo',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 127.0.0.1:9001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 9001
  }
}
/home/node/app/cli/build/src/utils/fetch-network-data.js:139
    if (nodeInfo === null || nodeInfo.nodeInfo === null) {
                                      ^

TypeError: Cannot read properties of undefined (reading 'nodeInfo')
    at fetchNodeInfo (/home/node/app/cli/build/src/utils/fetch-network-data.js:139:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/node/app/cli/build/src/node-commands.js:174:34
node@a93bff51db2f:~/app$
`
next attempt was ok.

**Comment by MichaelBa** [comment] 2023-04-14 13:17
As I understand, the original issue is related to:

> `operator-cli unstake`

Error in response:
> `{"jsonrpc":"2.0","id":53,"error":{"code":101,"message":"No reward endTime set, can't unstake node yet","data":{"originalError":{"status":400}}}}`

At first I received an error that is described in the initial post, some time later, this one.
If original post error shows that something is simply overloaded, this error looks like related to code.

**Comment by rafalbujak** [comment] 2023-04-14 15:21
> I have seen this ame error as @Balasuriya55 plus in my metamask this issue: ![Bez tytułu](https://user-images.githubusercontent.com/35694443/231828756-67ebb3bf-ba5d-4948-b1dc-0f62cd3ba95a.jpg)
> 
> adding staiking is not possible at the moment and takes a very long time after the update to the new version.
> 
> in addition, immediately after starting the node showed me this erorr in the console
> 
> Error: `node@a93bff51db2f:~/app$ operator-cli start node@a93bff51db2f:~/app$ operator-cli status AxiosError: connect ECONNREFUSED 127.0.0.1:9001 at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14) at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25) at RedirectableRequest.emit (node:events:402:35) at ClientRequest.eventHandlers. (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24) at ClientRequest.emit (node:events:390:28) at Socket.socketErrorListener (node:_http_client:447:9) at Socket.emit (node:events:390:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21) { port: 9001, address: '127.0.0.1', syscall: 'connect', code: 'ECONNREFUSED', errno: -111, config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [ 'xhr', 'http' ], transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 2000, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, env: { FormData: [Function], Blob: null }, validateStatus: [Function: validateStatus], headers: AxiosHeaders { Accept: 'application/json, text/plain, _/_', 'User-Agent': 'axios/1.2.2', 'Accept-Encoding': 'gzip, compress, deflate, br' }, method: 'get', url: 'http://127.0.0.1:9001/nodeinfo', data: undefined }, request: <ref *1> Writable { _writableState: WritableState { objectMode: false, highWaterMark: 16384, finalCalled: false, needDrain: false, ending: false, ended: false, finished: false, destroyed: false, decodeStrings: true, defaultEncoding: 'utf8', length: 0, writing: false, corked: 0, sync: true, bufferProcessing: false, onwrite: [Function: bound onwrite], writecb: null, writelen: 0, afterWriteTickInfo: null, buffered: [], bufferedIndex: 0, allBuffers: true, allNoop: true, pendingcb: 0, constructed: true, prefinished: false, errorEmitted: false, emitClose: true, autoDestroy: true, errored: null, closed: false, closeEmitted: false, [Symbol(kOnFinished)]: [] }, _events: [Object: null prototype] { response: [Function: handleResponse], error: [Function: handleRequestError], socket: [Array] }, _eventsCount: 3, _maxListeners: undefined, _options: { maxRedirects: 21, maxBodyLength: Infinity, protocol: 'http:', path: '/nodeinfo', method: 'GET', headers: [Object: null prototype], agents: [Object], auth: undefined, beforeRedirect: [Function: dispatchBeforeRedirect], beforeRedirects: [Object], hostname: '127.0.0.1', port: '9001', agent: undefined, nativeProtocols: [Object], pathname: '/nodeinfo' }, _ended: true, _ending: true, _redirectCount: 0, _redirects: [], _requestBodyLength: 0, _requestBodyBuffers: [], _onNativeResponse: [Function (anonymous)], _currentRequest: ClientRequest { _events: [Object: null prototype], _eventsCount: 7, _maxListeners: undefined, outputData: [], outputSize: 0, writable: true, destroyed: false, _last: true, chunkedEncoding: false, shouldKeepAlive: false, maxRequestsOnConnectionReached: false, _defaultKeepAlive: true, useChunkedEncodingByDefault: false, sendDate: false, _removedConnection: false, _removedContLen: false, _removedTE: false, _contentLength: 0, _hasBody: true, _trailer: '', finished: true, _headerSent: true, _closed: false, socket: [Socket], _header: 'GET /nodeinfo HTTP/1.1\r\n' + 'Accept: application/json, text/plain, _/_\r\n' + 'User-Agent: axios/1.2.2\r\n' + 'Accept-Encoding: gzip, compress, deflate, br\r\n' + 'Host: 127.0.0.1:9001\r\n' + 'Connection: close\r\n' + '\r\n', _keepAliveTimeout: 0, _onPendingData: [Function: nop], agent: [Agent], socketPath: undefined, method: 'GET', maxHeaderSize: undefined, insecureHTTPParser: undefined, path: '/nodeinfo', _ended: false, res: null, aborted: false, timeoutCb: null, upgradeOrConnect: false, parser: null, maxHeadersCount: null, reusedSocket: false, host: '127.0.0.1', protocol: 'http:', _redirectable: [Circular *1], [Symbol(kCapture)]: false, [Symbol(kNeedDrain)]: false, [Symbol(corked)]: 0, [Symbol(kOutHeaders)]: [Object: null prototype] }, _currentUrl: 'http://127.0.0.1:9001/nodeinfo', _timeout: null, [Symbol(kCapture)]: false }, cause: Error: connect ECONNREFUSED 127.0.0.1:9001 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 9001 } } /home/node/app/cli/build/src/utils/fetch-network-data.js:139 if (nodeInfo === null || nodeInfo.nodeInfo === null) { ^
> 
> TypeError: Cannot read properties of undefined (reading 'nodeInfo') at fetchNodeInfo (/home/node/app/cli/build/src/utils/fetch-network-data.js:139:39) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async /home/node/app/cli/build/src/node-commands.js:174:34 node@a93bff51db2f:~/app$ ` next attempt was ok.

Update, finaly after 5h transaktion was confirmed and now it is staked.

**Comment by swarna1101** [comment] 2024-01-18 05:28
this issue has been successfully resolved in the latest version of our network.

**Closed as completed by swarna1101** 2024-01-18 05:28 UTC
