### ISSUE TITLE
Validator GUI Pages Randomly Not Loading ```Application error: a client-side exception has occurred```

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#94] opened 2023-02-22 01:54 UTC
Application error: a client-side exception has occurred - 22 February 2023

**Comment by AndreiW3b3** [comment] 2023-02-22 01:54
https://www.loom.com/share/808147444d9142a6905bf0a27815ea0f

**Comment by AndreiW3b3** [comment] 2023-02-22 01:56
https://nextjs.org/docs/messages/client-side-exception-occurred

**Comment by hryhorii1** [comment] 2023-02-23 21:18
Just got a such error a few times today as well

**Comment by MarcusWentz** [comment] 2023-02-24 03:37
@hryhorii1 

Can you share the web browser terminal error log in text form if you still have the issue?

**Comment by hryhorii1** [comment] 2023-02-24 18:50
Yes sure, it reproduces for me quit often when I refresh the page after some time when I started my node and then come to the Gui and refresh the page I get such error as on the screenshot:
<img width="1673" alt="Application error: a client-side exception has occurred 2023-02-24 20-49-20" src="https://user-images.githubusercontent.com/37250271/221266504-5e3f992f-876c-484e-b00d-050773a17370.png">

**Comment by wyzwanie** [comment] 2023-03-29 16:52
i've pinpointed issue further. when going to settings page app tries to fetch logs using `spawn ls`

![Screenshot from 2023-03-29 18-46-44](https://user-images.githubusercontent.com/59451058/228610605-bd07d6b7-8afa-46cf-ab26-7d23b783fc5c.png)
![Screenshot from 2023-03-29 18-49-08](https://user-images.githubusercontent.com/59451058/228610819-839f2251-b2c9-4913-837b-5d5553cea8f3.png)

and then app probably expects this e.map to be an array of some files but gets undefined or something.
```js
const objectOrArray = e.length ?? []
const safeMap = maybeArray.map(...)
```
since no sourcemaps are provided its hard to pinpoint whre it exactly occurs.

**Comment by swarna1101** [comment] 2023-11-18 07:56
The issue affecting validator nodes is acknowledged and being actively addressed by our development team. However, due to the intricacies involved in the fix, it necessitates additional refinement and validation before deployment. The team is diligently working on this to ensure a comprehensive and robust solution in the subsequent update after the next one.

**Closed as completed by swarna1101** 2023-11-18 07:56 UTC
Labels: Bug
